// Copyright (c) 2025 TAS
// All rights reserved

// LEDs & Switches
%define LEDS_DATAOUT_ADDR       0xF000
%define SWITCHES_DATAIN_ADDR    0xF004

// Timer
%define TIMER_RELOAD_ADDR       0xF100
%define TIMER_COUNTER_ADDR      0xF104
%define TIMER_CONTROL_ADDR      0xF108

// UART
%define UART_TXDATA_ADDR        0xF200
%define UART_RXDATA_ADDR        0xF204
%define UART_CONTROL_ADDR       0xF208

// PWM
%define PWM_RELOAD_ADDR         0xF300
%define PWM_DUTY_ADDR           0xF304
%define PWM_COUNTER_ADDR        0xF308
%define PWM_CONTROL_ADDR        0xF30C

// HDMI
%define HDMI_DATAOUT_ADDR       0xF400
%define HDMI_ADDRSET_ADDR       0xF404
%define HDMI_CONTROL_ADDR       0xF408
